[default]
optimizer = true
optimizer_runs = 200
cache = true
remappings = [
    "ds-test=lib/ds-test/src/",
    "solmate=lib/solmate/src/",
]
eth_rpc_url = "https://eth-mainnet.alchemyapi.io/v2/7p4KzWgfAW2gU_4xOoPT5mpxDdOgFycO"

[ci]
fuzz_runs = 20_000
